# Generated by Django 5.1.3 on 2024-11-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
