# Generated by Django 5.1.3 on 2024-11-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="Status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
