# Generated by Django 5.1.3 on 2024-11-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_enrollment_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("course", "student")},
        ),
    ]
