# Generated by Django 5.1.3 on 2024-11-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_enrollment_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseinstructor",
            unique_together={("course", "instructor")},
        ),
    ]
