# Generated by Django 5.1.3 on 2024-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_likes_courselikes_courserating_delete_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
