# Generated by Django 5.1.3 on 2024-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_course_likes_course_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="course",
        ),
        migrations.AddField(
            model_name="comments",
            name="course",
            field=models.ManyToManyField(related_name="comments", to="api.course"),
        ),
    ]
