# Generated by Django 5.1.3 on 2024-11-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_comments_course_comments_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="course",
        ),
        migrations.AlterField(
            model_name="courselikes",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
            preserve_default=False,
        ),
    ]
