# Generated by Django 5.1.3 on 2024-11-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_comments_course_alter_courselikes_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselikes",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
