# Generated by Django 5.1.3 on 2024-11-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_courselikes_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="CourseComments",
        ),
    ]
