# Generated by Django 5.1.3 on 2024-11-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_rename_comments_coursecomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomments",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
    ]
