# Generated by Django 5.1.3 on 2024-11-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_coursecomments_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="toatl_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
