# Generated by Django 5.1.3 on 2024-11-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_course_toatl_ratings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="toatl_ratings",
            new_name="total_ratings",
        ),
    ]
