# Generated by Django 5.1.3 on 2024-12-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_coursevideos_course_progresstracking"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProgressTracking",
            new_name="CourseProgressTracking",
        ),
    ]
