# Generated by Django 5.1.3 on 2024-12-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_quiz_question_quizattempt_questionattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="qualified",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="total_marks",
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="qualified_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.quiz",
            ),
        ),
        migrations.CreateModel(
            name="AnswerAttempt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.question",
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.quizattempt",
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz_attempt", "question")},
            },
        ),
        migrations.DeleteModel(
            name="QuestionAttempt",
        ),
    ]
