# Generated by Django 5.1.3 on 2024-12-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_quizattempt_qualified_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizattempt",
            unique_together=set(),
        ),
    ]
