# Generated by Django 5.1.3 on 2025-01-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_rename_instructor_course_instructors_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseVideos",
            new_name="CourseVideo",
        ),
    ]
